/** Extra titles merged into Smart-search tropes. Key = trope.keys[0] or chips[0]. */
export const TROPE_EXTRAS: Record<string, string[]> = {
  "time travel": [
    "Back to the Future",
    "Back to the Future Part II",
    "Back to the Future Part III",
    "The Terminator",
    "Terminator 2: Judgment Day",
    "12 Monkeys",
    "Looper",
    "Primer",
    "Predestination",
    "Timecrimes",
    "Tenet",
    "About Time",
    "The Time Traveler's Wife",
    "The Time Machine",
    "Time After Time",
    "Time Bandits",
    "Bill & Ted's Excellent Adventure",
    "Bill & Ted's Bogus Journey",
    "Hot Tub Time Machine",
    "Frequency",
    "Déjà Vu",
    "Safety Not Guaranteed",
    "Kate & Leopold",
    "Somewhere in Time",
    "Peggy Sue Got Married",
    "Midnight in Paris",
    "The Butterfly Effect",
    "Donnie Darko",
    "X-Men: Days of Future Past",
    "Avengers: Endgame",
    "Project Almanac",
    "The Adam Project",
    "Meet the Robinsons",
    "Star Trek IV: The Voyage Home",
    "Star Trek",
    "Planet of the Apes",
    "Army of Darkness",
    "Austin Powers: International Man of Mystery",
    "Frequently Asked Questions About Time Travel",
    "See You Yesterday",
    "When We First Met",
    "13 Going on 30",
    "Click",
    "The Lake House",
    "Men in Black 3",
    "Synchronic",
    "Triangle",
    "Coherence",
    "Mr. Nobody",
    "The Fountain",
    "Slaughterhouse-Five",
    "Interstellar",
    "Arrival",
    "Your Name",
    "The Girl Who Leapt Through Time",
    "Dark",
    "Doctor Who",
    "Outlander",
    "11.22.63",
    "Quantum Leap",
    "Loki",
    "Travelers",
    "Timeless",
    "Steins;Gate",
    "Erased",
  ],
  "time loop": [
    "Groundhog Day",
    "Palm Springs",
    "Edge of Tomorrow",
    "Source Code",
    "Happy Death Day",
    "Happy Death Day 2U",
    "Russian Doll",
    "The Map of Tiny Perfect Things",
    "Boss Level",
    "ARQ",
    "12:01",
    "Naked",
    "Repeaters",
    "Triangle",
    "The Endless",
    "Run Lola Run",
    "Premature",
    "Before I Fall",
    "The Girl Who Leapt Through Time",
    "Mondays",
  ],
  "time loop movies": [
    "Groundhog Day",
    "Palm Springs",
    "Edge of Tomorrow",
    "Source Code",
    "Happy Death Day",
    "Happy Death Day 2U",
    "Boss Level",
    "ARQ",
    "12:01",
    "Naked",
    "Triangle",
    "The Endless",
  ],
  "time travel romance": [
    "About Time",
    "The Time Traveler's Wife",
    "Somewhere in Time",
    "Peggy Sue Got Married",
    "Kate & Leopold",
    "Safety Not Guaranteed",
    "Midnight in Paris",
    "The Lake House",
    "Your Name",
    "When We First Met",
    "13 Going on 30",
    "The Map of Tiny Perfect Things",
    "Outlander",
    "Frequency",
  ],
  heist: [
    "Ocean's Eleven",
    "Ocean's Twelve",
    "Ocean's Thirteen",
    "The Italian Job",
    "Heat",
    "Inside Man",
    "Logan Lucky",
    "Now You See Me",
    "The Town",
    "Baby Driver",
    "Widows",
    "The Asphalt Jungle",
    "Reservoir Dogs",
    "The Usual Suspects",
    "Snatch",
    "Lock, Stock and Two Smoking Barrels",
    "Den of Thieves",
    "The Score",
    "The Bank Job",
    "Ronin",
    "Out of Sight",
    "Sexy Beast",
    "The Thomas Crown Affair",
    "Inception",
    "Army of Thieves",
    "Lupin",
    "Money Heist",
  ],
  "road trip": [
    "Thelma & Louise",
    "Dumb and Dumber",
    "Little Miss Sunshine",
    "Superbad",
    "Harold & Kumar Go to White Castle",
    "EuroTrip",
    "Due Date",
    "Planes, Trains and Automobiles",
    "Easy Rider",
    "Sideways",
    "Almost Famous",
    "Stand by Me",
    "We're the Millers",
    "Little Miss Sunshine",
    "Rain Man",
    "National Lampoon's Vacation",
    "Y Tu Mamá También",
    "Into the Wild",
    "The Motorcycle Diaries",
    "Paper Towns",
    "Nebraska",
    "Green Book",
    "Midnight Run",
    "O Brother, Where Art Thou?",
    "Mad Max: Fury Road",
    "Nomadland",
  ],
  satire: [
    "Dr. Strangelove",
    "Network",
    "The Death of Stalin",
    "Don't Look Up",
    "In the Loop",
    "Wag the Dog",
    "Thank You for Smoking",
    "The Menu",
    "Triangle of Sadness",
    "American Psycho",
    "Idiocracy",
    "Election",
    "Bulworth",
    "The Great Dictator",
    "Sorry to Bother You",
    "Jojo Rabbit",
    "The Truman Show",
    "Office Space",
    "Brazil",
    "Parasite",
    "The White Lotus",
    "Veep",
    "Succession",
  ],
  parody: [
    "Airplane!",
    "The Naked Gun",
    "Hot Shots!",
    "Scary Movie",
    "Austin Powers: International Man of Mystery",
    "Spaceballs",
    "Galaxy Quest",
    "Shaun of the Dead",
    "Hot Fuzz",
    "Walk Hard: The Dewey Cox Story",
    "Blazing Saddles",
    "Robin Hood: Men in Tights",
    "Superhero Movie",
    "Not Another Teen Movie",
    "This Is Spinal Tap",
    "Tropic Thunder",
    "21 Jump Street",
    "The World's End",
    "Life of Brian",
    "History of the World: Part I",
    "Three Amigos!",
    "Young Frankenstein",
    "Monty Python and the Holy Grail",
  ],
  "eat the rich": [
    "Parasite",
    "The Menu",
    "Triangle of Sadness",
    "Ready or Not",
    "The White Lotus",
    "Glass Onion",
    "Knives Out",
    "Saltburn",
    "The Platform",
    "Squid Game",
    "Succession",
    "The Hunt",
    "High-Rise",
    "Snowpiercer",
    "Us",
    "Joker",
  ],
  "buddy cop": [
    "Lethal Weapon",
    "Bad Boys",
    "Rush Hour",
    "21 Jump Street",
    "The Nice Guys",
    "Hot Fuzz",
    "The Other Guys",
    "Kiss Kiss Bang Bang",
    "Tango & Cash",
    "Beverly Hills Cop",
    "48 Hrs.",
    "Men in Black",
    "The Heat",
    "Ride Along",
    "Cop Out",
    "The Rookie",
  ],
  "found family": [
    "Guardians of the Galaxy",
    "The Goonies",
    "Lilo & Stitch",
    "The Umbrella Academy",
    "Stranger Things",
    "The Mandalorian",
    "Everything Everywhere All at Once",
    "The Sandlot",
    "Stand by Me",
    "The Lost Boys",
    "Ocean's Eleven",
    "The Lord of the Rings: The Fellowship of the Ring",
    "Harry Potter and the Sorcerer's Stone",
    "Coco",
    "Encanto",
    "Our Flag Means Death",
  ],
  "coming of age": [
    "Lady Bird",
    "The Perks of Being a Wallflower",
    "Stand by Me",
    "Moonlight",
    "Boyhood",
    "Eighth Grade",
    "Call Me by Your Name",
    "The Spectacular Now",
    "The Breakfast Club",
    "Dazed and Confused",
    "Almost Famous",
    "Moonrise Kingdom",
    "The Florida Project",
    "Mid90s",
    "Licorice Pizza",
    "Are You There God? It's Me, Margaret.",
    "The Edge of Seventeen",
    "Juno",
  ],
  "high school": [
    "Mean Girls",
    "10 Things I Hate About You",
    "Clueless",
    "Superbad",
    "Easy A",
    "Booksmart",
    "Lady Bird",
    "The Breakfast Club",
    "Heathers",
    "Ferris Bueller's Day Off",
    "American Pie",
    "Bring It On",
    "She's All That",
    "Can't Hardly Wait",
    "Election",
    "Rushmore",
    "Dazed and Confused",
    "Eighth Grade",
  ],
  survival: [
    "Cast Away",
    "The Revenant",
    "127 Hours",
    "Into the Wild",
    "The Martian",
    "Life of Pi",
    "The Grey",
    "Alive",
    "The Impossible",
    "All Is Lost",
    "Captain Phillips",
    "Gravity",
    "The Edge",
    "Jungle",
    "Arctic",
    "The Ritual",
    "Lord of the Flies",
  ],
  apocalypse: [
    "Children of Men",
    "Mad Max: Fury Road",
    "The Road",
    "A Quiet Place",
    "28 Days Later",
    "Station Eleven",
    "The Last of Us",
    "Snowpiercer",
    "I Am Legend",
    "World War Z",
    "The Book of Eli",
    "Dawn of the Planet of the Apes",
    "Contagion",
    "Leave the World Behind",
    "Threads",
    "On the Beach",
    "Waterworld",
  ],
  zombie: [
    "28 Days Later",
    "Shaun of the Dead",
    "Zombieland",
    "Train to Busan",
    "World War Z",
    "Dawn of the Dead",
    "The Walking Dead",
    "Night of the Living Dead",
    "28 Weeks Later",
    "Army of the Dead",
    "The Girl with All the Gifts",
    "#Alive",
    "Rec",
    "Return of the Living Dead",
    "Warm Bodies",
    "iZombie",
  ],
  vampire: [
    "Let the Right One In",
    "What We Do in the Shadows",
    "Interview with the Vampire",
    "Only Lovers Left Alive",
    "The Lost Boys",
    "Twilight",
    "Nosferatu",
    "Bram Stoker's Dracula",
    "Near Dark",
    "From Dusk Till Dawn",
    "Blade",
    "30 Days of Night",
    "A Girl Walks Home Alone at Night",
    "Byzantium",
    "True Blood",
    "The Vampire Diaries",
  ],
  "serial killer": [
    "Zodiac",
    "Se7en",
    "Mindhunter",
    "The Silence of the Lambs",
    "Memories of Murder",
    "No Country for Old Men",
    "American Psycho",
    "Zodiac",
    "The Ripper",
    "Monster",
    "Henry: Portrait of a Serial Killer",
    "Copycat",
    "The Snowman",
    "Extremely Wicked, Shockingly Evil and Vile",
    "Dahmer",
    "The Night Of",
  ],
  slasher: [
    "Halloween",
    "Scream",
    "A Nightmare on Elm Street",
    "Friday the 13th",
    "Psycho",
    "The Texas Chain Saw Massacre",
    "Child's Play",
    "Scream 2",
    "I Know What You Did Last Summer",
    "Urban Legend",
    "Happy Death Day",
    "X",
    "Pearl",
    "The Strangers",
    "You're Next",
    "Freaky",
  ],
  "folk horror": [
    "The Wicker Man",
    "Midsommar",
    "The Witch",
    "Apostle",
    "Kill List",
    "The Ritual",
    "Lamb",
    "The Blood on Satan's Claw",
    "Witchfinder General",
    "A Field in England",
    "The Village",
    "Wake Wood",
    "Men",
    "Enys Men",
    "The Third Day",
  ],
  "cosmic horror": [
    "The Thing",
    "Event Horizon",
    "Annihilation",
    "Color Out of Space",
    "The Void",
    "In the Mouth of Madness",
    "Underwater",
    "The Mist",
    "Prometheus",
    "Life",
    "From Beyond",
    "The Endless",
    "Resolution",
    "True Detective",
  ],
  "body horror": [
    "The Fly",
    "Videodrome",
    "Tetsuo: The Iron Man",
    "Raw",
    "Society",
    "Crimes of the Future",
    "Titane",
    "Possessor",
    "Eraserhead",
    "Tetsuo",
    "Slither",
    "The Brood",
    "Scanners",
    "Akira",
    "Alien",
  ],
  "dark academia": [
    "Dead Poets Society",
    "The Secret History",
    "Kill Your Darlings",
    "The Riot Club",
    "Atonement",
    "The Talented Mr. Ripley",
    "Cruel Intentions",
    "The Skulls",
    "The Prime of Miss Jean Brodie",
    "Maurice",
    "Brideshead Revisited",
    "Saltburn",
    "The Magicians",
    "A Separate Peace",
    "The History Boys",
  ],
  space: [
    "Interstellar",
    "The Martian",
    "Gravity",
    "Apollo 13",
    "Alien",
    "Aliens",
    "2001: A Space Odyssey",
    "Arrival",
    "Ad Astra",
    "Moon",
    "Sunshine",
    "Passengers",
    "First Man",
    "The Right Stuff",
    "Star Trek",
    "Star Wars",
    "Dune",
    "For All Mankind",
    "The Expanse",
  ],
  superhero: [
    "The Dark Knight",
    "Spider-Man: Into the Spider-Verse",
    "Iron Man",
    "The Avengers",
    "Logan",
    "Watchmen",
    "The Incredibles",
    "Black Panther",
    "Guardians of the Galaxy",
    "Spider-Man: Across the Spider-Verse",
    "The Batman",
    "Wonder Woman",
    "Deadpool",
    "The Boys",
    "Invincible",
    "Daredevil",
  ],
  noir: [
    "Chinatown",
    "The Maltese Falcon",
    "Double Indemnity",
    "L.A. Confidential",
    "Blade Runner",
    "Drive",
    "Nightcrawler",
    "Se7en",
    "The Big Sleep",
    "Touch of Evil",
    "Brick",
    "Memento",
    "Oldboy",
    "True Detective",
  ],
  courtroom: [
    "12 Angry Men",
    "To Kill a Mockingbird",
    "A Few Good Men",
    "My Cousin Vinny",
    "The Verdict",
    "Philadelphia",
    "Primal Fear",
    "A Time to Kill",
    "The Lincoln Lawyer",
    "Just Mercy",
    "Anatomy of a Murder",
    "Erin Brockovich",
    "The Trial of the Chicago 7",
  ],
  sports: [
    "Rocky",
    "Remember the Titans",
    "Moneyball",
    "Rudy",
    "The Blind Side",
    "Friday Night Lights",
    "Creed",
    "Million Dollar Baby",
    "Raging Bull",
    "The Fighter",
    "Ford v Ferrari",
    "Rush",
    "Challengers",
    "Ted Lasso",
  ],
  "enemies to lovers": [
    "Pride & Prejudice",
    "10 Things I Hate About You",
    "The Proposal",
    "You've Got Mail",
    "How to Lose a Guy in 10 Days",
    "When Harry Met Sally",
    "The Cutting Edge",
    "Twilight",
    "Beauty and the Beast",
    "Much Ado About Nothing",
    "Bridgerton",
    "New Girl",
    "The Hating Game",
  ],
  "slow burn romance": [
    "Before Sunrise",
    "Pride & Prejudice",
    "Past Lives",
    "Call Me by Your Name",
    "In the Mood for Love",
    "The Age of Innocence",
    "Normal People",
    "Portrait of a Lady on Fire",
    "When Harry Met Sally",
    "Carol",
    "Brokeback Mountain",
  ],
  "chosen one": [
    "Star Wars",
    "The Matrix",
    "Harry Potter and the Sorcerer's Stone",
    "Dune",
    "The Lord of the Rings: The Fellowship of the Ring",
    "The Hunger Games",
    "The NeverEnding Story",
    "The Golden Compass",
    "Eragon",
    "Percy Jackson & the Olympians: The Lightning Thief",
    "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
    "Willow",
    "Avatar",
  ],
  underdog: [
    "Rocky",
    "Rudy",
    "The Karate Kid",
    "Million Dollar Baby",
    "Remember the Titans",
    "Moneyball",
    "Cinderella Man",
    "Dodgeball",
    "Miracle",
    "Cool Runnings",
    "The Blind Side",
    "Creed",
    "Eddie the Eagle",
    "McFarland, USA",
  ],
  "fish out of water": [
    "Crocodile Dundee",
    "Coming to America",
    "Legally Blonde",
    "Elf",
    "The Intern",
    "Miss Congeniality",
    "My Big Fat Greek Wedding",
    "The Martian",
    "Splash",
    "Enchanted",
    "The Princess Diaries",
    "Big",
    "Trading Places",
    "The Terminal",
  ],
  "die hard": [
    "Die Hard",
    "Speed",
    "The Raid",
    "Dredd",
    "Olympus Has Fallen",
    "Under Siege",
    "Air Force One",
    "The Negotiator",
    "Passenger 57",
    "White House Down",
    "Skyscraper",
    "Sudden Death",
    "Captain Phillips",
  ],
  "non-linear": [
    "Pulp Fiction",
    "Memento",
    "21 Grams",
    "Irreversible",
    "Eternal Sunshine of the Spotless Mind",
    "Arrival",
    "The Prestige",
    "Mulholland Drive",
    "Donnie Darko",
    "Primer",
    "Dunkirk",
    "The Fountain",
    "Cloud Atlas",
  ],
  mockumentary: [
    "This Is Spinal Tap",
    "Best in Show",
    "What We Do in the Shadows",
    "Borat",
    "The Office",
    "Parks and Recreation",
    "Drop Dead Gorgeous",
    "Waiting for Guffman",
    "Popstar: Never Stop Never Stopping",
    "The Thick of It",
    "A Mighty Wind",
    "Documentary Now!",
    "Abbott Elementary",
    "American Vandal",
  ],
  "black comedy": [
    "In Bruges",
    "Fargo",
    "Dr. Strangelove",
    "The Death of Stalin",
    "Four Lions",
    "Heathers",
    "American Psycho",
    "The Menu",
    "Kind Hearts and Coronets",
    "Burn After Reading",
    "In the Loop",
    "Kiss Kiss Bang Bang",
    "Seven Psychopaths",
    "The Lobster",
    "Jojo Rabbit",
  ],
  "action comedy": [
    "Hot Fuzz",
    "21 Jump Street",
    "Rush Hour",
    "The Nice Guys",
    "Kingsman: The Secret Service",
    "Bad Boys",
    "The Other Guys",
    "Deadpool",
    "Spy",
    "The Hitman's Bodyguard",
    "Kiss Kiss Bang Bang",
    "Tropic Thunder",
    "True Lies",
  ],
  "horror comedy": [
    "Shaun of the Dead",
    "What We Do in the Shadows",
    "Tucker and Dale vs Evil",
    "Scary Movie",
    "The World's End",
    "Zombieland",
    "Ready or Not",
    "The Cabin in the Woods",
    "Beetlejuice",
    "Evil Dead II",
    "Army of Darkness",
    "Happy Death Day",
    "Freaky",
    "Bodies Bodies Bodies",
  ],
  cyberpunk: [
    "Blade Runner",
    "Blade Runner 2049",
    "The Matrix",
    "Akira",
    "Ghost in the Shell",
    "Minority Report",
    "Strange Days",
    "Johnny Mnemonic",
    "Altered Carbon",
    "Cyberpunk: Edgerunners",
    "Upgrade",
    "Ex Machina",
    "Ready Player One",
  ],
  dystopian: [
    "Children of Men",
    "1984",
    "The Hunger Games",
    "Brazil",
    "V for Vendetta",
    "Gattaca",
    "The Handmaid's Tale",
    "Snowpiercer",
    "Equilibrium",
    "THX 1138",
    "A Clockwork Orange",
    "Minority Report",
    "Black Mirror",
  ],
  "space opera": [
    "Star Wars",
    "The Empire Strikes Back",
    "Dune",
    "Guardians of the Galaxy",
    "Star Trek",
    "The Fifth Element",
    "Serenity",
    "Firefly",
    "The Expanse",
    "Andor",
    "Foundation",
    "Valerian and the City of a Thousand Planets",
  ],
};
