/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddonsRouteImport } from './routes/addons'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as ListRouteImport } from './routes/list'
import { Route as OptionsRouteImport } from './routes/options'
import { Route as SearchRouteImport } from './routes/search'
import { Route as YoutubeRouteImport } from './routes/youtube'
import { Route as ApiMediaRouteImport } from './routes/api/media'
import { Route as BrowseTypeRouteImport } from './routes/browse.$type'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as CollectionsIdRouteImport } from './routes/collections.$id'
import { Route as ProviderIdRouteImport } from './routes/provider.$id'
import { Route as TitleTypeIdRouteImport } from './routes/title.$type.$id'
import { Route as WatchTypeIdRouteImport } from './routes/watch.$type.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddonsRoute = AddonsRouteImport.update({
  id: '/addons',
  path: '/addons',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ListRoute = ListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionsRoute = OptionsRouteImport.update({
  id: '/options',
  path: '/options',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const YoutubeRoute = YoutubeRouteImport.update({
  id: '/youtube',
  path: '/youtube',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaRoute = ApiMediaRouteImport.update({
  id: '/api/media',
  path: '/api/media',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseTypeRoute = BrowseTypeRouteImport.update({
  id: '/browse/$type',
  path: '/browse/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollectionsRoute,
} as any)
const CollectionsIdRoute = CollectionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CollectionsRoute,
} as any)
const ProviderIdRoute = ProviderIdRouteImport.update({
  id: '/provider/$id',
  path: '/provider/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TitleTypeIdRoute = TitleTypeIdRouteImport.update({
  id: '/title/$type/$id',
  path: '/title/$type/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchTypeIdRoute = WatchTypeIdRouteImport.update({
  id: '/watch/$type/$id',
  path: '/watch/$type/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/addons': typeof AddonsRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/list': typeof ListRoute
  '/options': typeof OptionsRoute
  '/search': typeof SearchRoute
  '/youtube': typeof YoutubeRoute
  '/api/media': typeof ApiMediaRoute
  '/browse/$type': typeof BrowseTypeRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/provider/$id': typeof ProviderIdRoute
  '/collections/': typeof CollectionsIndexRoute
  '/title/$type/$id': typeof TitleTypeIdRoute
  '/watch/$type/$id': typeof WatchTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/addons': typeof AddonsRoute
  '/list': typeof ListRoute
  '/options': typeof OptionsRoute
  '/search': typeof SearchRoute
  '/youtube': typeof YoutubeRoute
  '/api/media': typeof ApiMediaRoute
  '/browse/$type': typeof BrowseTypeRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/provider/$id': typeof ProviderIdRoute
  '/collections': typeof CollectionsIndexRoute
  '/title/$type/$id': typeof TitleTypeIdRoute
  '/watch/$type/$id': typeof WatchTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/addons': typeof AddonsRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/list': typeof ListRoute
  '/options': typeof OptionsRoute
  '/search': typeof SearchRoute
  '/youtube': typeof YoutubeRoute
  '/api/media': typeof ApiMediaRoute
  '/browse/$type': typeof BrowseTypeRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/provider/$id': typeof ProviderIdRoute
  '/collections/': typeof CollectionsIndexRoute
  '/title/$type/$id': typeof TitleTypeIdRoute
  '/watch/$type/$id': typeof WatchTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/addons'
    | '/collections'
    | '/list'
    | '/options'
    | '/search'
    | '/youtube'
    | '/api/media'
    | '/browse/$type'
    | '/collections/$id'
    | '/provider/$id'
    | '/collections/'
    | '/title/$type/$id'
    | '/watch/$type/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/addons'
    | '/list'
    | '/options'
    | '/search'
    | '/youtube'
    | '/api/media'
    | '/browse/$type'
    | '/collections/$id'
    | '/provider/$id'
    | '/collections'
    | '/title/$type/$id'
    | '/watch/$type/$id'
  id:
    | '__root__'
    | '/'
    | '/addons'
    | '/collections'
    | '/list'
    | '/options'
    | '/search'
    | '/youtube'
    | '/api/media'
    | '/browse/$type'
    | '/collections/$id'
    | '/provider/$id'
    | '/collections/'
    | '/title/$type/$id'
    | '/watch/$type/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddonsRoute: typeof AddonsRoute
  CollectionsRoute: typeof CollectionsRouteWithChildren
  ListRoute: typeof ListRoute
  OptionsRoute: typeof OptionsRoute
  SearchRoute: typeof SearchRoute
  YoutubeRoute: typeof YoutubeRoute
  ApiMediaRoute: typeof ApiMediaRoute
  BrowseTypeRoute: typeof BrowseTypeRoute
  ProviderIdRoute: typeof ProviderIdRoute
  TitleTypeIdRoute: typeof TitleTypeIdRoute
  WatchTypeIdRoute: typeof WatchTypeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addons': {
      id: '/addons'
      path: '/addons'
      fullPath: '/addons'
      preLoaderRoute: typeof AddonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list': {
      id: '/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof ListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/options': {
      id: '/options'
      path: '/options'
      fullPath: '/options'
      preLoaderRoute: typeof OptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youtube': {
      id: '/youtube'
      path: '/youtube'
      fullPath: '/youtube'
      preLoaderRoute: typeof YoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media': {
      id: '/api/media'
      path: '/api/media'
      fullPath: '/api/media'
      preLoaderRoute: typeof ApiMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/$type': {
      id: '/browse/$type'
      path: '/browse/$type'
      fullPath: '/browse/$type'
      preLoaderRoute: typeof BrowseTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/collections/$id': {
      id: '/collections/$id'
      path: '/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof CollectionsIdRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/provider/$id': {
      id: '/provider/$id'
      path: '/provider/$id'
      fullPath: '/provider/$id'
      preLoaderRoute: typeof ProviderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/title/$type/$id': {
      id: '/title/$type/$id'
      path: '/title/$type/$id'
      fullPath: '/title/$type/$id'
      preLoaderRoute: typeof TitleTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$type/$id': {
      id: '/watch/$type/$id'
      path: '/watch/$type/$id'
      fullPath: '/watch/$type/$id'
      preLoaderRoute: typeof WatchTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CollectionsRouteChildren {
  CollectionsIdRoute: typeof CollectionsIdRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
}

const CollectionsRouteChildren: CollectionsRouteChildren = {
  CollectionsIdRoute: CollectionsIdRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
}

const CollectionsRouteWithChildren = CollectionsRoute._addFileChildren(
  CollectionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddonsRoute: AddonsRoute,
  CollectionsRoute: CollectionsRouteWithChildren,
  ListRoute: ListRoute,
  OptionsRoute: OptionsRoute,
  SearchRoute: SearchRoute,
  YoutubeRoute: YoutubeRoute,
  ApiMediaRoute: ApiMediaRoute,
  BrowseTypeRoute: BrowseTypeRoute,
  ProviderIdRoute: ProviderIdRoute,
  TitleTypeIdRoute: TitleTypeIdRoute,
  WatchTypeIdRoute: WatchTypeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
